In [25]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [26]:
df = pd.read_csv('pf_suvs_i302_1s2024.csv')
df

,Marca,Modelo,Año,Versión,Color,Tipo de combustible,Puertas,Transmisión,Motor,Tipo de carrocería,Kilómetros,Título,Precio,Moneda,Tipo de vendedor,Con cámara de retroceso
0,Peugeot,2008,2022.0,1.6 Feline Tip am20,Blanco,Nafta,5.0,Automática,1.6,SUV,23000 km,Peugeot 2008 1.6 Feline Tip am20,22499999.0,$,tienda,NaN
1,Peugeot,2008,2021.0,1.6 Allure,Marrón,Nafta,5.0,Manual,1.6,SUV,17000 km,Peugeot 2008 1.6 Allure,21999999.0,$,tienda,NaN
2,Peugeot,2008,2021.0,1.6 Allure,Marrón,Nafta,5.0,Manual,1.6,SUV,17500 km,Peugeot 2008 1.6 Allure,20500000.0,$,tienda,NaN
3,Peugeot,2008,2018.0,1.6 Feline,Blanco,Nafta,5.0,Manual,1.6,SUV,123600 km,Peugeot 2008 1.6 Feline,15000000.0,$,tienda,NaN
4,Peugeot,2008,2016.0,1.6 Thp Sport,Gris,Nafta,5.0,Manual,1.6,SUV,43000 km,Peugeot 2008 1.6 Thp Sport,12500000.0,$,tienda,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22372,Volvo,XC60,2012.0,2.0 T5 Awd Comfort 240cv,Gris,Nafta,5.0,Automática,2.0,SUV,300000 km,Volvo XC60 2.0 T5 Awd Comfort 240cv,15000.0,U$S,particular,NaN
22373,Volvo,XC60,2020.0,3.0 T6 High Luxury Awd,Negro,Nafta,5.0,Automática,3.0,SUV,18500 km,Volvo XC60 3.0 T6 High Luxury Awd,120000.0,U$S,particular,NaN
22374,Volvo,XC60,2018.0,2.5 T5 Inscription,Negro,Nafta,5.0,Automática,2.5,SUV,100000 km,Volvo XC60 2.5 T5 Inscription,53000.0,U$S,particular,NaN
22375,Volvo,XC60,2012.0,2.0 T5 Awd High Plus 240cv,Negro,Nafta,5.0,Automática,2.0,SUV,138000 km,Volvo XC60 2.0 T5 Awd High Plus 240cv,15000.0,U$S,particular,NaN
22376,Volvo,XC60,2017.0,2.0 T5 Inscription,Gris,Nafta,5.0,Automática,2.0,SUV,104000 km,Volvo XC60 2.0 T5 Inscription,33000000.0,$,particular,Sí

In [27]:
df = df.drop_duplicates().reset_index(drop=True)
df

,Marca,Modelo,Año,Versión,Color,Tipo de combustible,Puertas,Transmisión,Motor,Tipo de carrocería,Kilómetros,Título,Precio,Moneda,Tipo de vendedor,Con cámara de retroceso
0,Peugeot,2008,2022.0,1.6 Feline Tip am20,Blanco,Nafta,5.0,Automática,1.6,SUV,23000 km,Peugeot 2008 1.6 Feline Tip am20,22499999.0,$,tienda,NaN
1,Peugeot,2008,2021.0,1.6 Allure,Marrón,Nafta,5.0,Manual,1.6,SUV,17000 km,Peugeot 2008 1.6 Allure,21999999.0,$,tienda,NaN
2,Peugeot,2008,2021.0,1.6 Allure,Marrón,Nafta,5.0,Manual,1.6,SUV,17500 km,Peugeot 2008 1.6 Allure,20500000.0,$,tienda,NaN
3,Peugeot,2008,2018.0,1.6 Feline,Blanco,Nafta,5.0,Manual,1.6,SUV,123600 km,Peugeot 2008 1.6 Feline,15000000.0,$,tienda,NaN
4,Peugeot,2008,2016.0,1.6 Thp Sport,Gris,Nafta,5.0,Manual,1.6,SUV,43000 km,Peugeot 2008 1.6 Thp Sport,12500000.0,$,tienda,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21746,Volvo,XC60,2012.0,2.0 T5 Awd Comfort 240cv,Gris,Nafta,5.0,Automática,2.0,SUV,300000 km,Volvo XC60 2.0 T5 Awd Comfort 240cv,15000.0,U$S,particular,NaN
21747,Volvo,XC60,2020.0,3.0 T6 High Luxury Awd,Negro,Nafta,5.0,Automática,3.0,SUV,18500 km,Volvo XC60 3.0 T6 High Luxury Awd,120000.0,U$S,particular,NaN
21748,Volvo,XC60,2018.0,2.5 T5 Inscription,Negro,Nafta,5.0,Automática,2.5,SUV,100000 km,Volvo XC60 2.5 T5 Inscription,53000.0,U$S,particular,NaN
21749,Volvo,XC60,2012.0,2.0 T5 Awd High Plus 240cv,Negro,Nafta,5.0,Automática,2.0,SUV,138000 km,Volvo XC60 2.0 T5 Awd High Plus 240cv,15000.0,U$S,particular,NaN
21750,Volvo,XC60,2017.0,2.0 T5 Inscription,Gris,Nafta,5.0,Automática,2.0,SUV,104000 km,Volvo XC60 2.0 T5 Inscription,33000000.0,$,particular,Sí

In [28]:
# Convertir los kilómetros a enteros
df['Kilómetros'] = df['Kilómetros'].str.replace(' km', '').str.replace('.', '').astype(int)
df

C:\Users\elmat\AppData\Local\Temp\ipykernel_22056\1455288787.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Kilómetros'] = df['Kilómetros'].str.replace(' km', '').str.replace('.', '').astype(int)

,Marca,Modelo,Año,Versión,Color,Tipo de combustible,Puertas,Transmisión,Motor,Tipo de carrocería,Kilómetros,Título,Precio,Moneda,Tipo de vendedor,Con cámara de retroceso
0,Peugeot,2008,2022.0,1.6 Feline Tip am20,Blanco,Nafta,5.0,Automática,1.6,SUV,23000,Peugeot 2008 1.6 Feline Tip am20,22499999.0,$,tienda,NaN
1,Peugeot,2008,2021.0,1.6 Allure,Marrón,Nafta,5.0,Manual,1.6,SUV,17000,Peugeot 2008 1.6 Allure,21999999.0,$,tienda,NaN
2,Peugeot,2008,2021.0,1.6 Allure,Marrón,Nafta,5.0,Manual,1.6,SUV,17500,Peugeot 2008 1.6 Allure,20500000.0,$,tienda,NaN
3,Peugeot,2008,2018.0,1.6 Feline,Blanco,Nafta,5.0,Manual,1.6,SUV,123600,Peugeot 2008 1.6 Feline,15000000.0,$,tienda,NaN
4,Peugeot,2008,2016.0,1.6 Thp Sport,Gris,Nafta,5.0,Manual,1.6,SUV,43000,Peugeot 2008 1.6 Thp Sport,12500000.0,$,tienda,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21746,Volvo,XC60,2012.0,2.0 T5 Awd Comfort 240cv,Gris,Nafta,5.0,Automática,2.0,SUV,300000,Volvo XC60 2.0 T5 Awd Comfort 240cv,15000.0,U$S,particular,NaN
21747,Volvo,XC60,2020.0,3.0 T6 High Luxury Awd,Negro,Nafta,5.0,Automática,3.0,SUV,18500,Volvo XC60 3.0 T6 High Luxury Awd,120000.0,U$S,particular,NaN
21748,Volvo,XC60,2018.0,2.5 T5 Inscription,Negro,Nafta,5.0,Automática,2.5,SUV,100000,Volvo XC60 2.5 T5 Inscription,53000.0,U$S,particular,NaN
21749,Volvo,XC60,2012.0,2.0 T5 Awd High Plus 240cv,Negro,Nafta,5.0,Automática,2.0,SUV,138000,Volvo XC60 2.0 T5 Awd High Plus 240cv,15000.0,U$S,particular,NaN
21750,Volvo,XC60,2017.0,2.0 T5 Inscription,Gris,Nafta,5.0,Automática,2.0,SUV,104000,Volvo XC60 2.0 T5 Inscription,33000000.0,$,particular,Sí

In [36]:
# Obtener todos los modelos de Tracker que sen 0km
df2 = df[(df['Modelo'] == 'Tracker') & (df['Kilómetros'] == 0) & (df['Año'] == 2021)]
df2

,Marca,Modelo,Año,Versión,Color,Tipo de combustible,Puertas,Transmisión,Motor,Tipo de carrocería,Kilómetros,Título,Precio,Moneda,Tipo de vendedor,Con cámara de retroceso
18820,Chevrolet,Tracker,2021.0,1.2 Premier Turbo At,Gris,Nafta,5.0,Automática,1.2,SUV,0,Chevrolet Tracker 1.2 Premier Turbo At,33190900.0,$,tienda,Sí
18839,Chevrolet,Tracker,2021.0,1.2 Premier Turbo At,Blanco,Nafta,5.0,Automática,1.2,SUV,0,Chevrolet Tracker 1.2 Premier Turbo At,33100900.0,$,tienda,Sí
18982,Chevrolet,Tracker,2021.0,1.2 Premier Turbo At,Azul,Nafta,5.0,Automática,1.2,SUV,0,Chevrolet Tracker 1.2 Premier Turbo At,31500000.0,$,tienda,NaN
18983,Chevrolet,Tracker,2021.0,1.2 Ltz Turbo At,Blanco,Nafta,5.0,Automática,1.2,SUV,0,Chevrolet Tracker 1.2 Ltz Turbo At,27489900.0,$,tienda,No
19244,Chevrolet,Tracker,2021.0,1.2 Turbo Mt,Blanco,Nafta,5.0,Manual,1.2,SUV,0,Chevrolet Tracker 1.2 Turbo Mt,28000000.0,$,concesionaria,NaN
19340,Chevrolet,Tracker,2021.0,1.2 Turbo Mt,Blanco,Nafta,5.0,Manual,1.2,SUV,0,Chevrolet Tracker 1.2 Turbo Mt,25344902.0,$,concesionaria,NaN
19468,Chevrolet,Tracker,2021.0,1.2 Turbo At,Blanco,Nafta,5.0,Automática,1.2,SUV,0,Chevrolet Tracker 1.2 Turbo At,27040900.0,$,concesionaria,No
19555,Chevrolet,Tracker,2021.0,1.2 Turbo Mt,Blanco,Nafta,5.0,Manual,1.2,SUV,0,Chevrolet Tracker 1.2 Turbo Mt,21900000.0,$,concesionaria,No
19569,Chevrolet,Tracker,2021.0,1.2 Premier Turbo At,Plateado,Nafta,5.0,Automática,1.2,SUV,0,Chevrolet Tracker 1.2 Premier Turbo At,36500000.0,$,concesionaria,No
19590,Chevrolet,Tracker,2021.0,1.2 Turbo At,A elegir,Nafta,5.0,Automática,1.2,SUV,0,Chevrolet Tracker 1.2 Turbo At,27972022.0,$,concesionaria,No
19612,Chevrolet,Tracker,2021.0,1.2 Premier Turbo At,NaN,Nafta,5.0,Automática,1.2,SUV,0,Chevrolet Tracker 1.2 Premier Turbo At,32859932.0,$,concesionaria,No